//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryPR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CityTbl()
        {
            this.UserTbls = new HashSet<UserTbl>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public int StateId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual StateTbl StateTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTbl> UserTbls { get; set; }
    }
}
