//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroceryPR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTbl
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNumber { get; set; }
        public string WhatsAppNumber { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int CountryId { get; set; }
        public int StateId { get; set; }
        public long CityId { get; set; }
        public string Landmark { get; set; }
        public string SocityName { get; set; }
        public string WingName { get; set; }
        public string FlatNumber { get; set; }
        public Nullable<System.Guid> Token { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
        public string UserName { get; set; }
    
        public virtual CityTbl CityTbl { get; set; }
        public virtual CountryTbl CountryTbl { get; set; }
        public virtual StateTbl StateTbl { get; set; }
    }
}
